#!/usr/bin/env python

#Written by Cru3 7/29/2016

#second import platform is cleaner
from sys import platform as operatingsystem
import platform
import os

#art

print ("""\
 ____ ____ ____    _____ _ _ ____ __   __
/ ___|  __|  __)  /  __) )( (  __| |  |  |
\___ \) _) ) _)   \___ ) __ () _)| |__|  |__
(____(____|____|  /____|_)(_(____)____/\____)

Local Privilege Escalation Framework 1.0
Written by Cru3, Appropriate Credit to Exploit Authors""")


#cross-platform system check and info.
#"in" statement is more flexible than == for os's like linux, linux2, and linux 3

cleanertext = "\n"

if "linux" in operatingsystem:
        print cleanertext + "Target details as follows: OS, Hostname, Version, Release, Architecture." + cleanertext
	print platform.uname()

elif "win" in operatingsystem:
	print cleanertext + "Target details as follows: OS, Hostname, Version, Release, Architecture." + cleanertext
	print platform.uname()

elif "darwin" in operatingsystem:
	print cleanertext + "Target details as follows: OS, Hostname, Version, Release, Architecture." + cleanertext
	print platform.uname()

elif "linux" or "win" or "darwin" not in operatingsystem:
	print cleanertext + "Operating system not recognized. BSD support to be added later. No automated exploitation available. OS, Hostname, Version, Release, Architecture below." + formatting
	print platform.uname()
