#!/usr/bin/env python

#Written by Cru3 7/29/2016

#second import platform is cleaner
from sys import platform as operatingsystem
import platform
import os

#art

print ("""\
 ____ ____ ____    _____ _ _ ____ __   __
/ ___|  __|  __)  /  __) )( (  __| |  |  |
\___ \) _) ) _)   \___ ) __ () _)| |__|  |__
(____(____|____|  /____|_)(_(____)____/\____)

SeeShell: Local Privilege Escalation Tool Alpha
Written by Cru3, Appropriate Credit to Exploit Authors
You are hereby warned that authorized and unauthorized exploitation of systems can immediately result in destruction of property, irrecoverable loss of data, and potentially unwanted access to computer systems. The author claims no responsibility for any losses, damages, or unwanted side-effects from the use of this tool or associated exploits.
Of all evil I deem you capable: Therefore I want good from you... -  Friedrich Nietzsche""")

#cross-platform system check and info.
#"in" statement is more flexible than == for os responses like linux, linux2, and linux3

cleanertext = "\n"
targetdetails = "Target details as follows: OS, Hostname, Version, Release, Architecture."

if "linux" in operatingsystem:
	print cleanertext + targetdetails + cleanertext
	print platform.uname()

elif "win" in operatingsystem:
	print cleanertext + targetdetails + cleanertext
	print platform.uname()

elif "darwin" in operatingsystem:
	print cleanertext + targetdetails + cleanertext
	print platform.uname()

elif "linux" or "win" or "darwin" not in operatingsystem:
	print cleanertext + "Operating system not recognized. BSD support to be added later. No automated exploitation available. OS, Hostname, Version, Release, Architecture below." + cleanertext
	print platform.uname()
